generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      Newupdate
    theme:            default
    list:
      title: New update List
      display: [  heading , message ,   starting_date ,  expire_date,created_at]
      object_actions:
        _edit: ~
        _delete: ~
    edit:
      title: create/edit New update
      display: [ heading , message ,    starting_date ,  expire_date,created_at]