generator:
  class:              sfPropelAdminGenerator
  param:
    model_class:      PostalCharges
    theme:            default
    list:
      title: 'Postal Charges'
      display: [id, charges, enablecountry, status]
      fields:
        enablecountry: {name: Country}
      object_actions:
        _delete: ~
        _edit: ~