default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, style.css, 960.css]

  javascripts:    [jquery.formatCurrency-1.3.0.min.js, i18n/jquery.formatCurrency.all.js ]

  has_layout:     on
  layout:         layout
